name: calories_py311
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.26
  - pandas>=2.2
  - scikit-learn>=1.4
  - lightgbm=4.4.*
  - catboost=1.2.*
  - xgboost=2.0.*
  - optuna>=3.6
  - shap>=0.44
  - ydata-profiling>=4.6
  - matplotlib>=3.9       
  - jupyterlab
  - pyarrow           
  - pip
  - pip:
      - polars